'use client'
import { useState } from 'react'
import { useParams } from 'next/navigation'
import { api } from '@/lib/api'
import toast from 'react-hot-toast'
import { Loader2, CheckCircle2, XCircle, Trophy, HelpCircle, BookOpen } from 'lucide-react'

interface Question {
  question: string
  options?: string[]
  correct?: string
  explanation?: string
  expected_answer?: string
  key_points?: string[]
  solution_steps?: string[]
  final_answer?: string
  concept?: string
}

interface QuizSet {
  id: string
  quiz_type: string
  questions: Question[]
}

export default function QuestionBankPage() {
  const { subjectId } = useParams<{ subjectId: string }>()
  const [quizSets, setQuizSets] = useState<QuizSet[]>([])
  const [activeSet, setActiveSet] = useState<QuizSet | null>(null)
  const [answers, setAnswers] = useState<Record<number, string>>({})
  const [showInsight, setShowInsight] = useState<Record<number, boolean>>({})
  const [submitted, setSubmitted] = useState(false)
  const [analysis, setAnalysis] = useState<{
    score: number
    detailed_feedback: string
    per_question: Array<{ question_index: number; is_correct: boolean; feedback: string }>
    wrong_concepts: string[]
  } | null>(null)
  const [generating, setGenerating] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [selectedTypes, setSelectedTypes] = useState<string[]>(['mcq', 'theory'])
  const [syncingNote, setSyncingNote] = useState<Record<number, boolean>>({})
  const [topicTitle, setTopicTitle] = useState('')

  const TYPES = [
    { id: 'mcq', label: 'MCQ', desc: '5 multiple choice' },
    { id: 'theory', label: 'Theory', desc: '4 logical questions' },
    { id: 'numerical', label: 'Numerical', desc: '3 calculation problems' },
  ]

  // ── Adaptive Learning: sync insight to notes ──
  const syncInsightToNotes = async (q: Question, isCorrect: boolean) => {
    try {
      await api.post(`/notes/${subjectId}/sync-insight`, {
        concept: q.concept || topicTitle || 'General',
        is_correct: isCorrect,
        explanation: q.explanation || q.expected_answer || 'Reviewed concept from quiz.',
      })
    } catch (err) {
      console.error('Failed to sync insight to notes', err)
    }
  }

  const handleGenerate = async () => {
    if (selectedTypes.length === 0) { toast.error('Select at least one type'); return }
    setGenerating(true)
    setActiveSet(null)
    setSubmitted(false)
    setAnalysis(null)
    setAnswers({})
    setShowInsight({})
    setSyncingNote({})
    try {
      const res = await api.post('/quiz/generate', { topic_id: null, quiz_types: selectedTypes, subject_id: subjectId })
      setQuizSets(res.data.quiz_sets)
      setActiveSet(res.data.quiz_sets[0])
      setTopicTitle(res.data.quiz_sets[0]?.quiz_type || 'General')
      toast.success('Quiz generated!')
    } catch {
      toast.error('Failed to generate quiz')
    } finally {
      setGenerating(false)
    }
  }

  const handleOptionSelect = async (qIndex: number, letter: string, q: Question) => {
    if (answers[qIndex]) return // Lock answer
    setAnswers((prev) => ({ ...prev, [qIndex]: letter }))
    setShowInsight((prev) => ({ ...prev, [qIndex]: true }))

    // Adaptive Learning Sync
    const correctLetter = q.correct ? q.correct.replace(')', '').trim().toUpperCase()[0] : ''
    const isCorrectUserAnswer = letter === correctLetter

    setSyncingNote(prev => ({ ...prev, [qIndex]: true }))
    await syncInsightToNotes(q, isCorrectUserAnswer)
    setSyncingNote(prev => ({ ...prev, [qIndex]: false }))
  }

  const handleSubmit = async () => {
    if (!activeSet) return
    const ans = activeSet.questions.map((_, i) => answers[i] || '')
    setSubmitting(true)
    try {
      const res = await api.post('/quiz/submit', { quiz_set_id: activeSet.id, answers: ans })
      setAnalysis(res.data.analysis)
      setSubmitted(true)
      toast.success('Quiz submitted! Knowledge gaps updated.')
    } catch {
      toast.error('Failed to submit')
    } finally {
      setSubmitting(false)
    }
  }

  const allAnswered = activeSet
    ? activeSet.questions.every((_, i) => !!answers[i])
    : false

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="max-w-2xl mx-auto px-5 py-6">
        <div className="mb-6">
          <h2 className="font-display text-xl text-lead mb-1">Question Bank</h2>
          <p className="text-sm text-muted">Generated by the Examiner Agent based on what you've learned.</p>
        </div>

        {/* Type selector + generate */}
        {!activeSet && !generating && (
          <div className="bg-surface border border-border rounded-xl p-5 mb-6">
            <p className="text-xs text-muted font-mono mb-3">Select question types</p>
            <div className="flex gap-3 mb-5">
              {TYPES.map((t) => (
                <button
                  key={t.id}
                  onClick={() =>
                    setSelectedTypes((prev) =>
                      prev.includes(t.id) ? prev.filter((x) => x !== t.id) : [...prev, t.id]
                    )
                  }
                  className={`flex-1 p-3 rounded-lg border text-left transition-all cursor-pointer ${
                    selectedTypes.includes(t.id)
                      ? 'border-accent bg-accent/8'
                      : 'border-border hover:border-accent/40'
                  }`}
                >
                  <p className={`text-xs font-medium mb-0.5 ${selectedTypes.includes(t.id) ? 'text-lead' : 'text-slate-900'}`}>
                    {t.label}
                  </p>
                  <p className="text-[11px] text-muted">{t.desc}</p>
                </button>
              ))}
            </div>
            <button
              onClick={handleGenerate}
              disabled={generating || selectedTypes.length === 0}
              className="w-full py-3 bg-lead text-paper rounded-lg text-sm font-medium hover:bg-lead/90 transition-all disabled:opacity-40 flex items-center justify-center gap-2 cursor-pointer"
            >
              {generating ? <><Loader2 size={14} className="animate-spin" /> Generating…</> : 'Generate Quiz →'}
            </button>
          </div>
        )}

        {generating && (
          <div className="space-y-4 animate-pulse">
            <div className="p-4 bg-muted/10 rounded-lg text-center text-sm text-muted">
              Examiner agent is building your test...
            </div>
            {[1, 2, 3].map((_, i) => <div key={i} className="h-32 bg-surface border border-border rounded-xl"></div>)}
          </div>
        )}

        {/* Set tabs */}
        {quizSets.length > 1 && (
          <div className="flex gap-2 mb-5">
            {quizSets.map((s) => (
              <button
                key={s.id}
                onClick={() => { setActiveSet(s); setAnswers({}); setSubmitted(false); setAnalysis(null); setShowInsight({}); setSyncingNote({}) }}
                className={`px-4 py-2 rounded-lg border text-xs capitalize transition-all cursor-pointer ${
                  activeSet?.id === s.id
                    ? 'border-accent bg-accent/8 text-lead font-medium'
                    : 'border-border text-muted hover:bg-surface'
                }`}
              >
                {s.quiz_type}
              </button>
            ))}
          </div>
        )}

        {/* Score banner */}
        {submitted && analysis && (
          <div className={`rounded-xl p-4 mb-6 border flex items-center gap-3 ${
            analysis.score >= 70 ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'
          }`}>
            <Trophy size={20} className={analysis.score >= 70 ? 'text-green-600' : 'text-red-500'} />
            <div className="flex-1">
              <p className={`font-medium text-sm ${analysis.score >= 70 ? 'text-green-700' : 'text-red-600'}`}>
                Score: {analysis.score.toFixed(0)}%
              </p>
              <p className="text-xs text-muted mt-0.5">{analysis.detailed_feedback}</p>
            </div>
            {analysis.wrong_concepts?.length > 0 && (
              <div className="text-right">
                <p className="text-[11px] text-muted">Weak areas</p>
                <p className="text-xs text-red-500">{analysis.wrong_concepts.join(', ')}</p>
              </div>
            )}
          </div>
        )}

        {/* Questions */}
        {activeSet && !generating && (
          <div className="space-y-6 pb-20">
            {activeSet.questions.map((q, i) => {
              const answered = !!answers[i]
              const showInsightBox = showInsight[i] || submitted

              let isCorrectUserAnswer = false
              let correctLetter = ''
              if (q.options && q.correct) {
                correctLetter = q.correct.replace(')', '').trim().toUpperCase()[0]
                isCorrectUserAnswer = answers[i] === correctLetter
              }

              return (
                <div key={i} className="bg-white border border-border rounded-xl p-5 shadow-sm">
                  <div className="flex items-start justify-between gap-3 mb-4">
                    <p className="text-sm font-medium text-slate-900 leading-snug">
                      <span className="text-muted font-mono mr-2">Q{i + 1}.</span>
                      {q.question}
                    </p>
                  </div>

                  {/* MCQ options */}
                  {activeSet.quiz_type === 'mcq' && q.options && (
                    <div className="space-y-2">
                      {q.options.map((opt, j) => {
                        const letter = ['A', 'B', 'C', 'D', 'E'][j]
                        const isSelected = answers[i] === letter
                        const isCorrectOpt = letter === correctLetter

                        let btnClass = 'border-border hover:border-accent bg-white text-slate-900'
                        if (answered) {
                          if (isCorrectOpt) btnClass = 'border-green-500 bg-green-50 text-green-800'
                          else if (isSelected && !isCorrectOpt) btnClass = 'border-red-500 bg-red-50 text-red-800'
                          else btnClass = 'border-border opacity-50 bg-white text-slate-500'
                        }

                        return (
                          <button
                            key={j}
                            onClick={() => handleOptionSelect(i, letter, q)}
                            disabled={answered}
                            className={`w-full text-left px-4 py-3 rounded-lg text-sm border transition-all flex items-center justify-between cursor-pointer disabled:cursor-default ${btnClass}`}
                          >
                            <span className="text-slate-900 font-medium">
                              <span className="font-mono text-xs mr-2 opacity-60">{letter})</span>
                              {opt.replace(/^[A-E]\)\s?/, '')}
                            </span>
                            {answered && isCorrectOpt && <CheckCircle2 className="text-green-500" size={16} />}
                            {answered && isSelected && !isCorrectOpt && <XCircle className="text-red-500" size={16} />}
                          </button>
                        )
                      })}
                    </div>
                  )}

                  {/* Theory / Numerical textarea */}
                  {(activeSet.quiz_type === 'theory' || activeSet.quiz_type === 'numerical') && (
                    <div className="space-y-3">
                      <textarea
                        value={answers[i] || ''}
                        onChange={(e) => !answered && setAnswers({ ...answers, [i]: e.target.value })}
                        disabled={answered}
                        placeholder="Write your answer / reasoning here..."
                        rows={3}
                        className="w-full resize-none px-4 py-3 bg-white border border-border rounded-lg text-sm text-slate-900 placeholder:text-muted/40 focus:outline-none focus:border-accent transition-colors disabled:opacity-60"
                      />
                      {!showInsightBox && (
                        <button
                          onClick={() => {
                            if (answers[i]) {
                              setShowInsight({ ...showInsight, [i]: true })
                              syncInsightToNotes(q, false)
                            }
                          }}
                          disabled={!answers[i]}
                          className="text-xs bg-lead text-white px-4 py-2 rounded-lg disabled:opacity-50 cursor-pointer hover:bg-lead/90 transition-colors"
                        >
                          Check Reasoning
                        </button>
                      )}
                    </div>
                  )}

                  {/* Teacher's Insight Pop-up */}
                  {showInsightBox && (
                    <div className={`mt-4 p-4 rounded-lg border ${!q.options || isCorrectUserAnswer ? 'border-accent/30 bg-accent/5' : 'border-red-200 bg-red-50/50'}`}>
                      <div className="flex items-center gap-2 mb-2">
                        <HelpCircle size={14} className={!q.options || isCorrectUserAnswer ? 'text-accent' : 'text-red-500'} />
                        <span className="text-xs font-bold uppercase tracking-wider text-slate-800 font-mono">
                          Teacher's Insight
                        </span>
                        {syncingNote[i] && (
                          <span className="ml-auto flex items-center gap-1 text-[10px] text-muted">
                            <Loader2 size={10} className="animate-spin" /> syncing…
                          </span>
                        )}
                        {!syncingNote[i] && showInsight[i] && (
                          <span className="ml-auto flex items-center gap-1 text-[10px] text-green-600">
                            <BookOpen size={10} /> saved to notes
                          </span>
                        )}
                      </div>

                      {q.options && (
                        <div className={`text-sm font-semibold mb-2 ${isCorrectUserAnswer ? 'text-green-700' : 'text-red-600'}`}>
                          {isCorrectUserAnswer ? '✓ Correct!' : `✗ Incorrect — The correct answer is ${correctLetter})`}
                        </div>
                      )}

                      {q.explanation && <p className="text-sm text-slate-800 mb-2">{q.explanation}</p>}
                      {q.expected_answer && (
                        <div className="mb-2">
                          <span className="text-xs font-semibold text-muted">Expected Approach: </span>
                          <span className="text-sm text-slate-800">{q.expected_answer}</span>
                        </div>
                      )}
                      {q.solution_steps && (
                        <div className="mb-2">
                          <span className="text-xs font-semibold text-muted">Solution Steps: </span>
                          <ul className="list-decimal pl-4 mt-1">
                            {q.solution_steps.map((s, k) => <li key={k} className="text-sm text-slate-800 mb-1">{s}</li>)}
                          </ul>
                          {q.final_answer && <p className="text-sm font-medium text-lead mt-2">Target Answer: {q.final_answer}</p>}
                        </div>
                      )}
                      {q.key_points && (
                        <ul className="list-disc pl-4 mt-2">
                          {q.key_points.map((kp, k) => <li key={k} className="text-xs text-slate-700 opacity-80">{kp}</li>)}
                        </ul>
                      )}
                    </div>
                  )}
                </div>
              )
            })}

            {!submitted && (
              <div className="sticky bottom-0 left-0 w-full pt-4 pb-4 bg-gradient-to-t from-[#fdfcf7] via-[#fdfcf7] to-transparent">
                <button
                  onClick={handleSubmit}
                  disabled={!allAnswered || submitting}
                  className="w-full py-3 bg-lead text-paper rounded-xl text-sm font-medium hover:bg-lead/90 transition-all disabled:opacity-40 flex items-center justify-center gap-2 cursor-pointer shadow-lg"
                >
                  {submitting ? <><Loader2 size={14} className="animate-spin" /> Analyzing Knowledge Gaps…</> : 'Finish & Analyze Knowledge Gaps →'}
                </button>
              </div>
            )}

            {submitted && (
              <div className="pt-4 pb-4">
                <button
                  onClick={() => {
                    setAnswers({})
                    setSubmitted(false)
                    setAnalysis(null)
                    setActiveSet(null)
                    setQuizSets([])
                    setShowInsight({})
                    setSyncingNote({})
                  }}
                  className="w-full py-3 border border-border rounded-xl text-sm text-muted hover:text-ink transition-colors cursor-pointer"
                >
                  Start New Quiz
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}